language: python
services:
  - docker
env:
  global:
    - DOCKER_TAG=${TRAVIS_COMMIT}

jobs:
  include:
  - python: "3.6"
    env: PYTHON_VERSION="3.6"
  - python: "3.7"
    env: PYTHON_VERSION="3.7"
  - python: "3.8"
    env: PYTHON_VERSION="3.8"

install:
  - make build

script:
  - make unit-test
  - make system-test
