sudo: required
language: python
services:
  - docker

env:
  global:
    # Docker
    - DOCKER_REPOSITORY=dask-lightgbm

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile.test

install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} -f Dockerfile.test --pull=true .

script:
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} pytest /app/dask_lightgbm
  - docker-compose up --abort-on-container-exit
