sudo: required
services:
  - docker

env:
  global:
    # Docker
    - DOCKER_REPOSITORY=dask-lightgbm

jobs:
  include:
    - stage: "Prepare env"
      script: docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} -f Dockerfile.test --pull=true .
    - stage: "Unit tests"
      script: docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} pytest /app/dask_lightgbm
    - stage: "System tests"
      script:
        - |
          docker-compose up
          docker run -it --link dask-lightgbm_scheduler_1:scheduler --network dask-lightgbm_default dask-lightgbm pytest /app/system_tests -ss
