version: '3.1'

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: dask-lightgbm
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: dask-lightgbm
    hostname: dask-worker
    command: ["dask-worker", "--nprocs", "2", "--nthreads", "2", "scheduler:8786"]

  client:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: dask-lightgbm
    hostname: dask-client
    command: ["pytest", "/app/system_tests"]
